### ISSUE TITLE
User Story 35, Merchant Dashboard displays Orders

### ISSUE THREAD

**Issue by stellakunzang** [sagemlee/monster_shop_2003#13]
As a merchant employee
When I visit my merchant dashboard ("/merchant")
If any users have pending orders containing items I sell
Then I see a list of these orders.
Each order listed includes the following information:
- the ID of the order, which is a link to the order show page ("/merchant/orders/15")
- the date the order was made
- the total quantity of my items in the order
- the total value of my items for that order

**Comment by stellakunzang** [comment]
This has so much difficult shit going on, I just need a place to keep track of it all before my head explodes! 

- [x] Multiply the price of each item by the quantity of that item purchased before sending the sum of the price of all items to the view. 

- [x] Add status column to orders that denotes if it is pending, shipped, etc. Can use enums?

- [x] Only return orders in AR methods that have pending status 

- [ ] Add column to item_orders with boolean denoting whether the order is fulfilled. Not needed for this user story, but just in my head and wanted to put it somewhere.

- [x] Break into smaller methods to be used for each bullet in the user story, rather than trying to do it in 1. Iterate over order # rather than merchant, with 1 method in merchant controller to get all the order numbers, and the rest of the methods in the appropriate controller! 

- [ ] The route provided in the user story doesn't exist yet and I'm not sure I understand what/how to do it. This is nested resource, and related to the type of user that is logged-in (in this case merchant employee)

**Comment by sagemlee** [comment]
1. I'm loving these markdown check boxes. 2. Wow there is a lot going on here. Just had a posse meeting with some folks who heavily encouraged pseudo coding and flowcharts.So I think writing this down into manageable chunks was definitely a good idea. But take it step by step!! Follow those errors.

**Comment by stellakunzang** [comment]
Holy cow, I finished it! Ended up using .inject for the first time, wow what a doozey!
