### ISSUE TITLE
User Story 17, Items Index Page

### ISSUE THREAD

**Issue by stellakunzang** [sagemlee/monster_shop_2003#2]
As any kind of user on the system
I can visit the items catalog ("/items")
I see all items in the system except disabled items

The item image is a link to that item's show page

**Comment by stellakunzang** [comment]
I am having trouble testing that the image is a link. I visited the local host and everything is working, but can't find the magic words for Capybara/RSpec to click on the image. Spent about an hour googling, so I'm going to move on to the next User Story and park this here to return to later. Please let me know if anyone has ideas or expertise!

**Comment by sagemlee** [comment]
Stella, maybe try tying an "id/class" to your image link? It looks like you may be able to do that, and in your test do something like find("class you have created").click

I got the idea from this post https://www.suffix.be/blog/click-image-in-link-capybara/   it mentions doing something similar.

**Comment by stellakunzang** [comment]
Holy cow, Sage you are an angel! That totally worked. In the image tag I just changed the word `alt` to `id` and instead of `find(img...).click` used `click_link(id)`.  YOU SAVED THE DAY TWICE TODAY, I AM SO PLEASED!
